/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'iqvw64e.sys'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
struct _GUID
{
  unsigned int Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 2 */
typedef struct _GUID GUID;

/* 3 */
struct RUNTIME_FUNCTION
{
  void *__ptr32 FunctionStart;
  void *__ptr32 FunctionEnd;
  void *__ptr32 UnwindInfo;
};

/* 4 */
struct UNWIND_INFO_HDR
{
  char Ver3_Flags;
  char PrologSize;
  char CntUnwindCodes;
  char FrReg_FrRegOff;
};

/* 5 */
struct UNWIND_CODE
{
  char PrologOff;
  char OpCode_OpInfo;
};

/* 7 */
typedef unsigned __int16 USHORT;

/* 10 */
typedef unsigned __int16 wchar_t;

/* 9 */
typedef wchar_t WCHAR;

/* 8 */
typedef WCHAR *PWSTR;

/* 6 */
struct _UNICODE_STRING
{
  USHORT Length;
  USHORT MaximumLength;
  PWSTR Buffer;
};

/* 16 */
typedef int LONG;

/* 15 */
union _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$D43038B1DD00167268319662DF7D50CE
{
  volatile LONG Lock;
  LONG LockNV;
};

/* 18 */
typedef unsigned __int8 UCHAR;

/* 17 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$147445C0E4E68EEE8CC57231FACAF18E
{
  UCHAR Type;
  UCHAR Signalling;
  UCHAR Size;
  UCHAR Reserved1;
};

/* 21 */
struct _DISPATCHER_HEADER::$::$::$C455783609593A5FC0070ED780464C2D::$F32BA6C812E0F769F09938C2098D009F
{
  unsigned __int8 Absolute : 1;
  unsigned __int8 Wake : 1;
  unsigned __int8 EncodedTolerableDelay : 6;
};

/* 20 */
union _DISPATCHER_HEADER::$::$C40575DFC387C8F4117E2F825EAF6417::$C455783609593A5FC0070ED780464C2D
{
  UCHAR TimerControlFlags;
  struct
  {
    unsigned __int8 Absolute : 1;
    unsigned __int8 Wake : 1;
    unsigned __int8 EncodedTolerableDelay : 6;
  };
};

/* 23 */
struct _DISPATCHER_HEADER::$::$::$05D45FD30F9D93B8752762EBBCB0BF0A::$AA905F972124AC55790449D6420AAEA5
{
  unsigned __int8 Index : 6;
  unsigned __int8 Inserted : 1;
  unsigned __int8 Expired : 1;
};

/* 22 */
union _DISPATCHER_HEADER::$::$C40575DFC387C8F4117E2F825EAF6417::$05D45FD30F9D93B8752762EBBCB0BF0A
{
  UCHAR TimerMiscFlags;
  struct
  {
    unsigned __int8 Index : 6;
    unsigned __int8 Inserted : 1;
    unsigned __int8 Expired : 1;
  };
};

/* 19 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$C40575DFC387C8F4117E2F825EAF6417
{
  UCHAR TimerType;
  union
  {
    UCHAR TimerControlFlags;
    struct
    {
      unsigned __int8 Absolute : 1;
      unsigned __int8 Wake : 1;
      unsigned __int8 EncodedTolerableDelay : 6;
    };
  };
  UCHAR Hand;
  union
  {
    UCHAR TimerMiscFlags;
    struct
    {
      unsigned __int8 Index : 6;
      unsigned __int8 Inserted : 1;
      unsigned __int8 Expired : 1;
    };
  };
};

/* 26 */
struct _DISPATCHER_HEADER::$::$::$BC95C1005138DD6C54C311F6EA5D109E::$79EE8220B9CBCC15640D116F9688A663
{
  unsigned __int8 Timer2Inserted : 1;
  unsigned __int8 Timer2Expiring : 1;
  unsigned __int8 Timer2CancelPending : 1;
  unsigned __int8 Timer2SetPending : 1;
  unsigned __int8 Timer2Running : 1;
  unsigned __int8 Timer2Disabled : 1;
  unsigned __int8 Timer2ReservedFlags : 2;
};

/* 25 */
union _DISPATCHER_HEADER::$::$93871522DA2DA651F6EE6945327295BD::$BC95C1005138DD6C54C311F6EA5D109E
{
  UCHAR Timer2Flags;
  struct
  {
    unsigned __int8 Timer2Inserted : 1;
    unsigned __int8 Timer2Expiring : 1;
    unsigned __int8 Timer2CancelPending : 1;
    unsigned __int8 Timer2SetPending : 1;
    unsigned __int8 Timer2Running : 1;
    unsigned __int8 Timer2Disabled : 1;
    unsigned __int8 Timer2ReservedFlags : 2;
  };
};

/* 24 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$93871522DA2DA651F6EE6945327295BD
{
  UCHAR Timer2Type;
  union
  {
    UCHAR Timer2Flags;
    struct
    {
      unsigned __int8 Timer2Inserted : 1;
      unsigned __int8 Timer2Expiring : 1;
      unsigned __int8 Timer2CancelPending : 1;
      unsigned __int8 Timer2SetPending : 1;
      unsigned __int8 Timer2Running : 1;
      unsigned __int8 Timer2Disabled : 1;
      unsigned __int8 Timer2ReservedFlags : 2;
    };
  };
  UCHAR Timer2ComponentId;
  UCHAR Timer2RelativeId;
};

/* 29 */
struct _DISPATCHER_HEADER::$::$::$1728BC3AACECDC2141D1E32FE66EA23E::$3EFE0FF07DD77BBDEABCDA7FF0A75165
{
  unsigned __int8 Abandoned : 1;
  unsigned __int8 DisableIncrement : 1;
  unsigned __int8 QueueReservedControlFlags : 6;
};

/* 28 */
union _DISPATCHER_HEADER::$::$5BEE508906071BCCD40638FEAF58F305::$1728BC3AACECDC2141D1E32FE66EA23E
{
  UCHAR QueueControlFlags;
  struct
  {
    unsigned __int8 Abandoned : 1;
    unsigned __int8 DisableIncrement : 1;
    unsigned __int8 QueueReservedControlFlags : 6;
  };
};

/* 27 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$5BEE508906071BCCD40638FEAF58F305
{
  UCHAR QueueType;
  union
  {
    UCHAR QueueControlFlags;
    struct
    {
      unsigned __int8 Abandoned : 1;
      unsigned __int8 DisableIncrement : 1;
      unsigned __int8 QueueReservedControlFlags : 6;
    };
  };
  UCHAR QueueSize;
  UCHAR QueueReserved;
};

/* 32 */
struct _DISPATCHER_HEADER::$::$::$0E76FCEEB5609B75E7D96C8D89B50E90::$289C34DDD4E6D8A579D3E1CDF74CD890
{
  unsigned __int8 CycleProfiling : 1;
  unsigned __int8 CounterProfiling : 1;
  unsigned __int8 GroupScheduling : 1;
  unsigned __int8 AffinitySet : 1;
  unsigned __int8 Tagged : 1;
  unsigned __int8 EnergyProfiling : 1;
  unsigned __int8 SchedulerAssist : 1;
  unsigned __int8 ThreadReservedControlFlags : 1;
};

/* 31 */
union _DISPATCHER_HEADER::$::$C4D4F6505347955A7E49BDD08F2B07A4::$0E76FCEEB5609B75E7D96C8D89B50E90
{
  UCHAR ThreadControlFlags;
  struct
  {
    unsigned __int8 CycleProfiling : 1;
    unsigned __int8 CounterProfiling : 1;
    unsigned __int8 GroupScheduling : 1;
    unsigned __int8 AffinitySet : 1;
    unsigned __int8 Tagged : 1;
    unsigned __int8 EnergyProfiling : 1;
    unsigned __int8 SchedulerAssist : 1;
    unsigned __int8 ThreadReservedControlFlags : 1;
  };
};

/* 34 */
struct _DISPATCHER_HEADER::$::$::$49B2F56B82B650C36577DFA53D44488C::$5B46111089229E54AB036CC97FD77231
{
  unsigned __int8 ActiveDR7 : 1;
  unsigned __int8 Instrumented : 1;
  unsigned __int8 Minimal : 1;
  unsigned __int8 Reserved4 : 3;
  unsigned __int8 UmsScheduled : 1;
  unsigned __int8 UmsPrimary : 1;
};

/* 33 */
union _DISPATCHER_HEADER::$::$C4D4F6505347955A7E49BDD08F2B07A4::$49B2F56B82B650C36577DFA53D44488C
{
  UCHAR DebugActive;
  struct
  {
    unsigned __int8 ActiveDR7 : 1;
    unsigned __int8 Instrumented : 1;
    unsigned __int8 Minimal : 1;
    unsigned __int8 Reserved4 : 3;
    unsigned __int8 UmsScheduled : 1;
    unsigned __int8 UmsPrimary : 1;
  };
};

/* 30 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$C4D4F6505347955A7E49BDD08F2B07A4
{
  UCHAR ThreadType;
  UCHAR ThreadReserved;
  union
  {
    UCHAR ThreadControlFlags;
    struct
    {
      unsigned __int8 CycleProfiling : 1;
      unsigned __int8 CounterProfiling : 1;
      unsigned __int8 GroupScheduling : 1;
      unsigned __int8 AffinitySet : 1;
      unsigned __int8 Tagged : 1;
      unsigned __int8 EnergyProfiling : 1;
      unsigned __int8 SchedulerAssist : 1;
      unsigned __int8 ThreadReservedControlFlags : 1;
    };
  };
  union
  {
    UCHAR DebugActive;
    struct
    {
      unsigned __int8 ActiveDR7 : 1;
      unsigned __int8 Instrumented : 1;
      unsigned __int8 Minimal : 1;
      unsigned __int8 Reserved4 : 3;
      unsigned __int8 UmsScheduled : 1;
      unsigned __int8 UmsPrimary : 1;
    };
  };
};

/* 36 */
typedef unsigned __int8 BOOLEAN;

/* 35 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$3EF41BFA0BF183FFCD9D039EF3AA2B7F
{
  UCHAR MutantType;
  UCHAR MutantSize;
  BOOLEAN DpcActive;
  UCHAR MutantReserved;
};

/* 14 */
union _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217
{
  union
  {
    volatile LONG Lock;
    LONG LockNV;
  };
  struct
  {
    UCHAR Type;
    UCHAR Signalling;
    UCHAR Size;
    UCHAR Reserved1;
  };
  struct
  {
    UCHAR TimerType;
    union
    {
      UCHAR TimerControlFlags;
      struct
      {
        unsigned __int8 Absolute : 1;
        unsigned __int8 Wake : 1;
        unsigned __int8 EncodedTolerableDelay : 6;
      };
    };
    UCHAR Hand;
    union
    {
      UCHAR TimerMiscFlags;
      struct
      {
        unsigned __int8 Index : 6;
        unsigned __int8 Inserted : 1;
        unsigned __int8 Expired : 1;
      };
    };
  };
  struct
  {
    UCHAR Timer2Type;
    union
    {
      UCHAR Timer2Flags;
      struct
      {
        unsigned __int8 Timer2Inserted : 1;
        unsigned __int8 Timer2Expiring : 1;
        unsigned __int8 Timer2CancelPending : 1;
        unsigned __int8 Timer2SetPending : 1;
        unsigned __int8 Timer2Running : 1;
        unsigned __int8 Timer2Disabled : 1;
        unsigned __int8 Timer2ReservedFlags : 2;
      };
    };
    UCHAR Timer2ComponentId;
    UCHAR Timer2RelativeId;
  };
  struct
  {
    UCHAR QueueType;
    union
    {
      UCHAR QueueControlFlags;
      struct
      {
        unsigned __int8 Abandoned : 1;
        unsigned __int8 DisableIncrement : 1;
        unsigned __int8 QueueReservedControlFlags : 6;
      };
    };
    UCHAR QueueSize;
    UCHAR QueueReserved;
  };
  struct
  {
    UCHAR ThreadType;
    UCHAR ThreadReserved;
    union
    {
      UCHAR ThreadControlFlags;
      struct
      {
        unsigned __int8 CycleProfiling : 1;
        unsigned __int8 CounterProfiling : 1;
        unsigned __int8 GroupScheduling : 1;
        unsigned __int8 AffinitySet : 1;
        unsigned __int8 Tagged : 1;
        unsigned __int8 EnergyProfiling : 1;
        unsigned __int8 SchedulerAssist : 1;
        unsigned __int8 ThreadReservedControlFlags : 1;
      };
    };
    union
    {
      UCHAR DebugActive;
      struct
      {
        unsigned __int8 ActiveDR7 : 1;
        unsigned __int8 Instrumented : 1;
        unsigned __int8 Minimal : 1;
        unsigned __int8 Reserved4 : 3;
        unsigned __int8 UmsScheduled : 1;
        unsigned __int8 UmsPrimary : 1;
      };
    };
  };
  struct
  {
    UCHAR MutantType;
    UCHAR MutantSize;
    BOOLEAN DpcActive;
    UCHAR MutantReserved;
  };
};

/* 38 */
struct _LIST_ENTRY
{
  struct _LIST_ENTRY *Flink;
  struct _LIST_ENTRY *Blink;
};

/* 37 */
typedef struct _LIST_ENTRY LIST_ENTRY;

/* 13 */
struct _DISPATCHER_HEADER
{
  union
  {
    union
    {
      volatile LONG Lock;
      LONG LockNV;
    };
    struct
    {
      UCHAR Type;
      UCHAR Signalling;
      UCHAR Size;
      UCHAR Reserved1;
    };
    struct
    {
      UCHAR TimerType;
      union
      {
        UCHAR TimerControlFlags;
        struct
        {
          unsigned __int8 Absolute : 1;
          unsigned __int8 Wake : 1;
          unsigned __int8 EncodedTolerableDelay : 6;
        };
      };
      UCHAR Hand;
      union
      {
        UCHAR TimerMiscFlags;
        struct
        {
          unsigned __int8 Index : 6;
          unsigned __int8 Inserted : 1;
          unsigned __int8 Expired : 1;
        };
      };
    };
    struct
    {
      UCHAR Timer2Type;
      union
      {
        UCHAR Timer2Flags;
        struct
        {
          unsigned __int8 Timer2Inserted : 1;
          unsigned __int8 Timer2Expiring : 1;
          unsigned __int8 Timer2CancelPending : 1;
          unsigned __int8 Timer2SetPending : 1;
          unsigned __int8 Timer2Running : 1;
          unsigned __int8 Timer2Disabled : 1;
          unsigned __int8 Timer2ReservedFlags : 2;
        };
      };
      UCHAR Timer2ComponentId;
      UCHAR Timer2RelativeId;
    };
    struct
    {
      UCHAR QueueType;
      union
      {
        UCHAR QueueControlFlags;
        struct
        {
          unsigned __int8 Abandoned : 1;
          unsigned __int8 DisableIncrement : 1;
          unsigned __int8 QueueReservedControlFlags : 6;
        };
      };
      UCHAR QueueSize;
      UCHAR QueueReserved;
    };
    struct
    {
      UCHAR ThreadType;
      UCHAR ThreadReserved;
      union
      {
        UCHAR ThreadControlFlags;
        struct
        {
          unsigned __int8 CycleProfiling : 1;
          unsigned __int8 CounterProfiling : 1;
          unsigned __int8 GroupScheduling : 1;
          unsigned __int8 AffinitySet : 1;
          unsigned __int8 Tagged : 1;
          unsigned __int8 EnergyProfiling : 1;
          unsigned __int8 SchedulerAssist : 1;
          unsigned __int8 ThreadReservedControlFlags : 1;
        };
      };
      union
      {
        UCHAR DebugActive;
        struct
        {
          unsigned __int8 ActiveDR7 : 1;
          unsigned __int8 Instrumented : 1;
          unsigned __int8 Minimal : 1;
          unsigned __int8 Reserved4 : 3;
          unsigned __int8 UmsScheduled : 1;
          unsigned __int8 UmsPrimary : 1;
        };
      };
    };
    struct
    {
      UCHAR MutantType;
      UCHAR MutantSize;
      BOOLEAN DpcActive;
      UCHAR MutantReserved;
    };
  };
  LONG SignalState;
  LIST_ENTRY WaitListHead;
};

/* 12 */
typedef struct _DISPATCHER_HEADER DISPATCHER_HEADER;

/* 11 */
struct _KEVENT
{
  DISPATCHER_HEADER Header;
};

/* 41 */
typedef int NTSTATUS;

/* 42 */
typedef void *PVOID;

/* 40 */
union _IO_STATUS_BLOCK::$77CEE0AF02806C16F943E6B3BF8ECA77
{
  NTSTATUS Status;
  PVOID Pointer;
};

/* 43 */
typedef unsigned __int64 ULONG_PTR;

/* 39 */
struct _IO_STATUS_BLOCK
{
  union
  {
    NTSTATUS Status;
    PVOID Pointer;
  };
  ULONG_PTR Information;
};

/* 45 */
typedef unsigned int ULONG;

/* 46 */
typedef void *HANDLE;

/* 47 */
typedef struct _UNICODE_STRING *PUNICODE_STRING;

/* 44 */
struct _OBJECT_ATTRIBUTES
{
  ULONG Length;
  HANDLE RootDirectory;
  PUNICODE_STRING ObjectName;
  ULONG Attributes;
  PVOID SecurityDescriptor;
  PVOID SecurityQualityOfService;
};

/* 50 */
typedef char CHAR;

/* 49 */
typedef CHAR *PCHAR;

/* 48 */
struct _STRING
{
  USHORT Length;
  USHORT MaximumLength;
  PCHAR Buffer;
};

/* 51 */
typedef struct _UNICODE_STRING UNICODE_STRING;

